### ISSUE TITLE
HTML build notes

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#158]
Hi @nelliemckesson I was writing you an e-mail but thought maybe best to write out my notes on the HTML build here (just did a pass over it). You are probably aware of most of these!

1. I could revamp the website, but I would prefer to keep the same urls. I would like to book to build to:

```
chapter-1-vectors/index.html
chapter-2-forces/index.html
etc...
```

rather than the current:

```
vectors.html
forces.html
etc...
````

2. The JS files (and everything necessary for `/book/` specifically fonts, css, etc) should get included in the build. . and end up in the assets folder? Something like:

```
assets/javascript/size-iframes.js
etc.
```

Then the template should reference their relative path so that it can be tested without being published to the site itself? ...and anything that is part of `natureofcode.com` (not in the `/book/`) directly can be referenced via the full url?

The goal is to be able to open up `/build2/` and have it look exactly like `natureofcode.com/book/`. Does that make sense?

3. Syntax highlighting (maybe [prism](https://prismjs.com/)?), I wonder what @runemadsen uses for his book?

4. Code splitting.

5. The layout looks off to me when I open the build, but this might be due to various path things that aren't set up correctly as in (2) above.

<img width="1233" alt="screen shot 2018-08-27 at 8 50 08 pm" src="https://user-images.githubusercontent.com/191758/44694329-d305d500-aa3a-11e8-8a57-7faea65ffc28.png">

**Comment by nelliemckesson** [comment]
Awesome, this is great. See https://github.com/shiffman/The-Nature-of-Code/pull/159 !

**Comment by joeyklee** [comment]
Hi All! Just wanted to make a note - maybe something that also gets addressed here (https://github.com/magicbookproject/magicbook), but I didn't manage to get this to build. 

In both node v5.8.0 and v10.15 I get the following after `npm install`:

```
➜  noc-book git:(master) ✗ magicbook build --config=magicbook.json
Config file detected: magicbook.json
buffer.js:140
    throw new TypeError('must start with number, buffer, array or string');
    ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:140:11)
    at new Buffer (buffer.js:62:10)
    at DestroyableTransform._transform (/Users/joeyklee/.nvm/versions/node/v5.8.0/lib/node_modules/magicbook/src/plugins/ids.js:59:25)
```

and 

```
  noc-book git:(master) ✗ magicbook build --config=magicbook.json
Config file detected: magicbook.json
buffer.js:207
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:207:11)
    at new Buffer (buffer.js:182:17)
    at DestroyableTransform._transform (/Users/joeyklee/.nvm/versions/node/v10.15.0/lib/node_modules/magicbook/src/plugins/ids.js:59:25)
```

Any chance ya'll might know what is happening? 

Thanks!

**Comment by joeyklee** [comment]
Hi there! 

Just revisiting this again. I've found that if I remove the `"plugins"` array from the magicbook.json, the build succeeds. 

I did `npm install magicbook-katex magicbook-codesplit` and tried to `magicbook build` but to no avail. The error mentioned above (`ERR_INVALID_ARG_TYPE`) is still returned. 

I'll keep poking around. 

Update:
I have a hunch that it could be related to the `through2` npm modules that is being used for the **addP5 plugin**. There's some notes here about issues with readableStream https://www.npmjs.com/package/through2

Using node.js v10.15.0

**Comment by joeyklee** [comment]
Hi All!

Just a note that @shiffman and I discovered. It seems that the `through2` library needs to be updated for the `magicbook`, `magicbook-katex`, and `magicbook-codesplit` since the `through2` dependency is currently breaking the build. 

If it is ok for you @runemadsen - I will make a PR to those respective libraries to version `3.0.1` :) Thanks for all your efforts on this project! 

Update, I've made PRs to the above mentioned:
- https://github.com/magicbookproject/magicbook-katex/pull/1
- https://github.com/magicbookproject/magicbook-codesplit/pull/1
- https://github.com/magicbookproject/magicbook/pull/22

**Comment by runemadsen** [comment]
Thanks @joeyklee 

I have merged all your PR's and published new versions on NPM of all the packages.

One note about JS and CSS assets: I am using `magicbook-webpack` for my book instead of the built in assets pipeline that uses sass, etc. Given how much things have changed these last few years, we might want to get rid of sass and just use webpack directly in `magicbook`. Perhaps I'll look at this when I have time at some point :)

**Comment by joeyklee** [comment]
@runemadsen - Oh yes! I noticed the `magicbook-webpack` in the magicbook organization. As this is the latest "standard" for bundling, etc, I agree this might be a nice way of keeping magicbook current. I'm not sure if this is currently the case in the magicbook, but it would be great to have things like hot-reloading.

**Comment by joeyklee** [comment]
Just fyi, I've made some PRs to the magicbook to use all the latest dependency versions. It seems my last PR didn't resolve the dependency issues properly. See: https://github.com/magicbookproject/magicbook/pull/23

**Comment by shiffman** [comment]
Moving this issue to noc-book-2 to continue any discussion there!
