### ISSUE TITLE
line-through class codesplit

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#80]
Fix codesplit `line-through` class which should only line-through the code and not the comment.  The comment to the right should not have the line:

<img width="691" alt="screen shot 2016-07-06 at 10 27 50 am" src="https://cloud.githubusercontent.com/assets/191758/16621475/5babaa3c-4364-11e6-8c79-c43d8b1a3ef0.png">

**Comment by alterebro** [comment]
This one is resolved with the commit 04db905

**Comment by shiffman** [comment]
I'm still seeing this in the render:

<img width="675" alt="screen shot 2016-07-11 at 10 35 39 am" src="https://cloud.githubusercontent.com/assets/191758/16734384/5aaf2684-4753-11e6-9c53-5f67642e67b1.png">

**Comment by alterebro** [comment]
mmm, it was working fine to me on 4 different browsers.
There's a small change now that should work everywhere.
